name: Template Validation
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate template
        id: validate-template
        uses: ./.github/actions/validate-template
        with:
          path: $GITHUB_WORKSPACE

      - name: Create comment
        if: steps.validate-template.outputs.status != 0
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.validate-template.outputs.detail }}
